### PR TITLE
Rename STACK into _STACK

### PR DESCRIPTION
**Pull request by marcocaberletti**
This PR is a "one line fix" that rename the STACK type into _STACK, resolving in this way the build error.
I'm not an OpenSSL expert and I haven't a test case that verify the consequences of this fix.
Can you watch this?

Thanks,
Marco

### CODE REVIEW

**Comment by msalle** [comment]
Hi Marco,

you can probably use `gss_cred_id_t` from gssapi.h instead of `gss_cred_id_desc *`.
You then don't need to redefine `gss_cred_id_desc` locally and that would prevent this fix altogether.
Furthermore, you need some updates for OpenSSL 1.1 to `struct gss_ctx_id_desc_struct`.
We should bring the code here back in sync with the [lcas-lcmaps-gt4-interface](https://ndpfsvn.nikhef.nl/viewvc/mwsec/trunk/lcas-lcmaps-gt4-interface/) code, on which this callout is loosely based.

**Comment by marcocaberletti** [comment]
Hi,
I think that you are the most experienced person on this argument, so you could submit a PR with the necessary fixes.
Every contribution is appreciated.

Marco

**Comment by msalle** [comment]
Hi Marco,
it's actually already on my todo list, how urgent is it, can it wait a week or two? I will have much more time then than now.
Mischa

**Comment by marcocaberletti** [comment]
Hi,
as far as I known, this is not urgent.

**Comment by msalle** [comment]
Ok thanks, I'll come back to it later then.

**Comment by msalle** [comment]
Hi,
I opened PR #3 which fixes this in the exact same way as lcas-lcmaps-gt4-interface. I haven't taken over your jenkins file and .gitignore patches to keep things clean. I'm planning to also cleanup all the compile-time warnings, once the openssl1.1 fixes are merged.

**Comment by msalle** [comment]
I'm closing this one as it has been replaced by #3
However, it seems there were a few other commits in this one which I'm not sure are still necessary, please open a new PR when we're indeed still missing bits,

**Pull request closed without merging**
